Implement match chat redirection
cuappdev/pear-ios pull request #170
Opened 2021-10-13 22:50 UTC by vianxnguyen

## Overview

Implement chat redirection for matched pair, added current user information to other profile screens.

## Changes Made

- Added reach out button to chat with matched pair
- Passed current user information to other user profiles, in case we need to implement chatting with other users.

## Test Coverage

Tested on device.

2021-10-13 22:52 UTC, ReadeP commented on Pear/Controller/CommunityViewController.swift
> +    private var currentUser : UserV2
no space between currentUser and :

2021-10-13 22:53 UTC, ReadeP commented on Pear/Controller/ChatViewController.swift
> +            self.navigationController?.pushViewController(ProfileViewController(user: self.currentUser, otherUserId: self.messageUser.id), animated: true)
Remove "self" before currentUser and messageUser

2021-10-13 22:54 UTC, ReadeP commented on Pear/Profile/MatchProfileViewController.swift
> +        navigationController?.pushViewController(ChatViewController(messageUser: matchedUser, currentUser: user), animated: true)
Indent this line

2021-10-13 22:55 UTC, ReadeP commented on Pear/Profile/ProfileViewController.swift
> +        print(otherUserId)
delete this print statement

2021-10-13 23:10 UTC, danielVebman requested changes
Great first PR Vivian! Let me know if you have any questions about my comments. Re-request my review once you finish making changes, and make sure to give most of your reviewers a chance to review your code before you merge!

2021-10-13 23:10 UTC, danielVebman commented on Pear/Controller/CommunityViewController.swift
> +
Delete whitespace

2021-10-13 23:10 UTC, danielVebman commented on Pear/Controller/CommunityViewController.swift
> +    private var currentUser: UserV2
If this isn't modified, make it `private let`

2021-10-13 23:10 UTC, danielVebman commented on Pear/Controller/TabPageViewController.swift
> +    private let communityViewController : UIViewController
Delete space before `:`, i.e.

```suggestion
    private let communityViewController: UIViewController
```

2021-10-13 23:10 UTC, danielVebman commented on Pear/Profile/MatchProfileViewController.swift
> +            make.bottom.equalTo(view.safeAreaLayoutGuide).inset(Constants.Onboarding.nextBottomPadding)
If this is very long, break up onto multiple lines.

2021-10-13 23:10 UTC, danielVebman commented on Pear/Profile/MatchProfileViewController.swift
> +
Delete newline

2021-10-13 23:10 UTC, danielVebman commented on Pear/Profile/MatchProfileViewController.swift
> +            }
Indentation off

2021-10-13 23:10 UTC, danielVebman commented on Pear/Profile/MatchProfileViewController.swift
> +            navigationController?.pushViewController(ChatViewController(messageUser: matchedUser, currentUser: user), animated: true)
Break up onto multiple lines. E.g.

```suggestion
            navigationController?.pushViewController(
                ChatViewController(
                    messageUser: matchedUser, 
                    currentUser: user
                ), 
                animated: true
            )
```

2021-10-13 23:10 UTC, danielVebman commented on Pear/Profile/ProfileViewController.swift
> +    private var otherUserId: Int
Why not let?

2021-10-13 23:10 UTC, danielVebman commented on Pear/Profile/ProfileViewController.swift
> +
delete whitespace

2021-10-13 23:10 UTC, danielVebman commented on Pear/Profile/ProfileViewController.swift
> +    private var otherUser: UserV2?
Having this optional variable and also having `otherUserId` is redundant. What if you made an enum with two states? 

```
private enum ProfileViewControllerUser {
    case userId(String)
    case user(UserV2)
}
```

Maybe this is unnecessary. Let me know your thoughts.

2021-10-14 00:58 UTC, danielVebman commented on Pear/Profile/ProfileViewController.swift
> +    private var otherUserId: Int
That doesn't matter. You can say

```
class X {
    private let y: Int
    init(y: Int) { self.y = y }
}
```

2021-10-14 02:04 UTC, danielVebman approved these changes
lgtm!

2021-10-14 02:04 UTC, danielVebman commented on Pear/Profile/ProfileViewController.swift
> +    private func setOtherUser(otherUserId: Int) {
I'd call this `getOtherUser`

2021-10-14 02:04 UTC, danielVebman commented
It would be ideal if you included screenshots and/or screen recordings in your PR description.

2021-10-18 02:07 UTC, merged